service: api-checkout-users

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  register:
    role: ${ssm:${self:custom.stage}-register-iam-role}
    description: 'Função de registro de usuario'
    handler: register/handler.register
    environment:
      DYNAMODB_USERS: ${ssm:${self:custom.stage}-dynamodb-users-table}
    events:
      - http:
          path: users
          method: post

  login:
    role: ${ssm:${self:custom.stage}-login-iam-role}
    description: 'Função de logar o user'
    handler: login/handler.login
    environment:
      DYNAMODB_USERS: ${ssm:${self:custom.stage}-dynamodb-users-table}
      JWT_SECRET: ${ssm:${self:custom.stage}-jwt-secret}
      EMAIL_GSI: ${ssm:${self:custom.stage}-email-gsi}
    events:
      - http:
          path: login
          method: post        
